version: "3.4"

services:
  db_mongo:
    container_name: mongo_nestTeste
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - redeInterna
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - "./src/database/mongo:/var/lib/mongodb/data"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: db_mongo
    networks:
     - redeInterna 

    depends_on: 
      - db_mongo

  node:
    container_name: node_nestTeste
    build: .
    command: npm run start:dev
    networks: 
      - redeInterna
    ports:
      - 3000:3000
    depends_on:
      - db_mongo
    volumes:
      - .:/usr/app

networks:
  redeInterna:
