version: "3.4"

services:
  db_mongo:
    container_name: mongo_nestTeste
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - redeInterna
    restart: on-failure
    volumes:
      - "./src/database/mongo:/var/lib/mongodb/data"

  node:
    container_name: node_nestTeste
    build: .
    networks: 
      - redeInterna
    ports:
      - 3333:3333
    depends_on:
      - db_mongo
    volumes:
      - .:usr/app

networks:
  redeInterna:
