version: '3.4'

services:
  db_mongo:
    container_name: mongo_nestTeste
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - redeInterna
    restart: always
    volumes:
      - './src/database/mongo:/var/lib/mongodb/data'

  node:
    container_name: node_nestTeste
    build: .
    command: 'sh /usr/src/app/start-up.sh'
    networks:
      - redeInterna
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - db_mongo
    volumes:
      - .:/usr/src/app

networks:
  redeInterna:
